name       : gnome-code-assistance
version    : 3.16.1
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-code-assistance/3.16/gnome-code-assistance-3.16.1.tar.xz : f6b7aae10afe150587c00d3db9e4d7503a489ca618930b9b6e3f81b5dafed353
license    : LGPL-3.0
summary    : Common code completion service
description: |
    gnome-code-assistance is a project which aims to provide common code assistance services for code editors (simple editors as well as IDEs). It is an effort to provide a centralized code-assistance as a service for the GNOME platform instead of having every editor implement their own solution.
builddeps  :
    - pkgconfig(libvala-0.32)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gee-0.8)
    - llvm-devel
    - python-simplejson
    - gjs
    - pkgconfig(python-3.5)
    - python3-dbus
    - vala
rundeps    :
    - python-simplejson
    - gjs
    - python3
    - python3-dbus
    - python3-gobject
setup      : |
    # TODO: Enable go + ruby
    %configure --disable-static \
               --enable-c \
               --enable-json \
               --enable-xml \
               --enable-vala \
               --enable-sh \
               --enable-python
build      : |
    %make
install    : |
    %make_install
