name       : gnome-code-assistance
version    : 3.16.1
release    : 5
source     :
    - git|https://git.gnome.org/browse/gnome-code-assistance.git : a46522ac93b0ff046a80b3672a51e2d20ac8d295
license    : LGPL-3.0
component  : desktop.gnome.doc
summary    : Common code completion service
description: |
    gnome-code-assistance is a project which aims to provide common code assistance services for code editors (simple editors as well as IDEs). It is an effort to provide a centralized code-assistance as a service for the GNOME platform instead of having every editor implement their own solution.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(python3)
    - llvm-devel
    - python3-gobject-devel
    - python-simplejson
    - gjs
    - golang
    - python3-dbus
    - vala
rundeps    :
    - python-simplejson
    - gjs
    - python3
    - python3-dbus
    - python3-gobject
setup      : |
    # TODO: Enable ruby (needs ruby dbus)
    %reconfigure --disable-static \
        --enable-c \
        --enable-go \
        --enable-json \
        --enable-xml \
        --enable-python \
        --enable-sh \
        --enable-vala
build      : |
    %make
install    : |
    %make_install
