name       : gnome-code-assistance
version    : 3.16.1
release    : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-code-assistance/3.16/gnome-code-assistance-3.16.1.tar.xz : f6b7aae10afe150587c00d3db9e4d7503a489ca618930b9b6e3f81b5dafed353
license    : LGPL-3.0
component  : desktop.gnome.doc
summary    : Common code completion service
description: |
    gnome-code-assistance is a project which aims to provide common code assistance services for code editors (simple editors as well as IDEs). It is an effort to provide a centralized code-assistance as a service for the GNOME platform instead of having every editor implement their own solution.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(python-3.5)
    - llvm-devel
    - python3-gobject-devel
    - python-simplejson
    - gjs
    - golang
    - python3-dbus
    - vala
rundeps    :
    - python-simplejson
    - gjs
    - python3
    - python3-dbus
    - python3-gobject
setup      : |
    # TODO: Enable ruby (needs ruby dbus)
    %patch -p1 < $pkgfiles/gnome-code-assistance-vala-0.36.patch
    %reconfigure --disable-static \
        --enable-c \
        --enable-go \
        --enable-json \
        --enable-xml \
        --enable-python \
        --enable-sh \
        --enable-vala
build      : |
    %make
install    : |
    %make_install
